### ISSUE TITLE
Color output issue with images on transparent backgrounds 

### ISSUE THREAD

**Issue by duhring** [goodtohear/BeatSheetStudio#100]
I'm getting blue images but it seems to affect only images with transparent backgrounds.

1. Create a slide 
2. Drag an image with a transparent background onto the card
3. Present that slide

Example: 
![Screenshot 2023-10-17 at 7 43 15 PM](https://github.com/goodtohear/BeatSheetStudio/assets/2724263/01e0dbda-29da-41dd-9f6c-1ff3ac316ca6)

**Comment by michaelforrest** [comment]
Fixed in f7dcf62d29d2cf60f856054e60ffcbbf84eb78de
