### ISSUE TITLE
Folder icon confusion

### ISSUE THREAD

**Issue by duhring** [goodtohear/BeatSheetStudio#18]
It might be a bug.

[Video](https://youtu.be/5vAoQy0Ch9c)

**Comment by michaelforrest** [comment]
Link doesn't work?

**Comment by duhring** [comment]
Nada. Sent from my iPhoneOn Jul 13, 2023, at 10:55 PM, Michael Forrest ***@***.***> wrote:﻿
Link doesn't work?

**Comment by michaelforrest** [comment]
I mean the youtube link. But actually I think I see what happened now...

**Comment by duhring** [comment]
Folder icon bugFolder icon bugyoutu.beBetter?JohnSent from my iPhoneOn Jul 14, 2023, at 2:10 AM, Michael Forrest ***@***.***> wrote:﻿
I mean the youtube link. But actually I think I see what happened now...

**Comment by duhring** [comment]
Here is the URL

Folder icon bug

https://youtu.be/5vAoQy0Ch9c

**Comment by michaelforrest** [comment]
It's okay, I'd found it, but you'd put some url Markdown on it so when I clicked it it tried to go to "url" instead of the YouTube url. 

For future reference, in Markdown you you can either paste a plain link (preferable) or put the url like this `[Video](https://youtu.be/5vAoQy0Ch9c)`.

**Comment by michaelforrest** [comment]
I've labelled these icons now so this shouldn't be an issue.

The icon is called "macwindow" so 🤷
