### ISSUE TITLE
CPU load report

### ISSUE THREAD

**Issue by duhring** [goodtohear/BeatSheetStudio#22]
The fan kicked in and the CPU rating of over 100% caught my eye.

<img width="1006" alt="Screenshot 2023-07-15 at 9 28 01 PM" src="https://github.com/goodtohear/BeatSheetStudio/assets/2724263/a3016b36-7cba-447e-afb8-bfce3c23ff79">

Energy impact is also high

<img width="1033" alt="Screenshot 2023-07-15 at 9 30 41 PM" src="https://github.com/goodtohear/BeatSheetStudio/assets/2724263/a1564a4c-394e-4124-b6cd-3c6e8ac13f1f">

I am running a window share (with the activity monitor selected), with PiP. I also have Air Server mirrored from the iPad, showing Video Pencil. I have the BSS output displayed on my Shoot (iPhone). I am on a Zoom session (After Hours) as well.

![IMG_096AD4DA6F0E-1](https://github.com/goodtohear/BeatSheetStudio/assets/2724263/159d844d-bbea-4075-a156-33b46449098f)

**Comment by michaelforrest** [comment]
I'm hoping the worst problems are resolved by the fix for https://github.com/goodtohear/BeatSheetStudio/issues/16
