### ISSUE TITLE
What about Light Mode too?

### ISSUE THREAD

**Issue by duhring** [goodtohear/BeatSheetStudio#23]
John Ittleson couldn't see the contents of the "desktop stack". Turns out his Appearance was set to Light. 

![image](https://github.com/goodtohear/BeatSheetStudio/assets/2724263/c9c55cf2-ad1f-4bc9-b072-a87a3991dfb8)

We switched to Dark and he's a happy camper now

![image](https://github.com/goodtohear/BeatSheetStudio/assets/2724263/a8202682-0084-46f9-a0cd-30d72f0e5497)

**Comment by michaelforrest** [comment]
Last thing I did on Friday as I was rushing out of the office! I'll be tweaking this today (hopefully).
