### ISSUE TITLE
New files not showing without restarting app

### ISSUE THREAD

**Issue by duhring** [goodtohear/BeatSheetStudio#3]
I saved and closed a new .bss sheet and…
It doesn’t show up on the “Welcome” page
From this page I must open a sheet before sharing a screen, etc.
An artifact overlay is still active even after closing the sheet

Some stumbling around, here

https://youtu.be/t-0f-yWyfvY

Cheers,

John

**Comment by michaelforrest** [comment]
@samilao101 Another instance of needing a good way to hook system-level updates into our ObservableObject state. 
In `BeatSheetApp` I use 
```
.onForeground {
  recentFiles = NSDocumentController.shared.recentDocumentURLs
}
```
to update the recent files list but this does not pick up changes to the recentDocumentURLs (I don't think it even triggers when the app enters the foreground!). 

Need to find out how macOS wants this to be done.
