### ISSUE TITLE
Bits and pieces

### ISSUE THREAD

**Issue by duhring** [goodtohear/BeatSheetStudio#33]
The new build required removing screen share permissions and reboots. I found I could run a sheet better than via the interface.

- cameras came through ok, I rebooted shoot on one iPhone
- Displays did not show through the UI, only came up from sheet cards during presentation (see video)

https://www.youtube.com/watch?v=hVAbB2qe8To

You can link to the same video from multiple issues (timestamped links would be appreciated!).
<img width="396" alt="Screenshot 2023-07-24 at 9 20 36 AM" src="https://github.com/goodtohear/BeatSheetStudio/assets/2724263/52e78865-1fde-4ef4-a836-dc721eb73106">

**Comment by duhring** [comment]
Another run through:

- Running a show brings up window and display views that are called by Cards
- The "back button" doesn't function, but I can choose a Tile to bring up a given Card
- The BSS UI is not consistently picking displays and windows

[https://youtu.be/IEgISLsnvfo](url)

**Comment by michaelforrest** [comment]
Notes on [first video](https://www.youtube.com/watch?v=hVAbB2qe8To)
* Took a couple of times to get a website to come up on the desktop
* Can't see screen from the Desktop Sharing button, only from the card

**Comment by michaelforrest** [comment]
Notes on [second video](https://www.youtube.com/watch?v=hVAbB2qe8To)
* Can't pick up desktop shares through interface
* Back doesn't work

The display navigation is related to #8

**Comment by michaelforrest** [comment]
Closed this issue as invalid and created the two bug reports I need.

**Comment by michaelforrest** [comment]
If I missed something when extracting issues from here, please add as a separate bug report (and reference this issue by typing `#33` so I can find the video again)
