### ISSUE TITLE
Memory running low

### ISSUE THREAD

**Issue by duhring** [goodtohear/BeatSheetStudio#4]
I was using Air Server to display a panorama from my phone, when I saw I was using 13GB of my 16GB of memory. 

The “WindowServer” process was doing 10GB of damage. When I killed Air Server it went down a bit… when I killed BSS, it went down a lot! The “Memory Pressure” graph (attached) shows the cliff when BSS closed.
<img width="640" alt="Screenshot 2023-07-10 at 12 39 11 PM 2" src="https://github.com/goodtohear/BeatSheetStudio/assets/2724263/c95851f4-ec2c-475a-82c3-5207b1b26de1">

**Comment by michaelforrest** [comment]
Could you explain the steps you had taken? You were sharing the AirServer window? Was this from a card or directly selected?

**Comment by michaelforrest** [comment]
Closing but will re-open if I get better steps to reproduce.
