### ISSUE TITLE
Frame rate issues when editing in real time

### ISSUE THREAD

**Issue by duhring** [goodtohear/BeatSheetStudio#5]
https://youtu.be/zV8egAgfIBY

I noticed a typo on screen. When I edited it, the camera hit the wall until I moved to a new card in the sheet.

Also in the video, I noted the Shoot (iPhone12) preview was hung and needed a restart to get out of Portrait mode.

**Comment by michaelforrest** [comment]
Notes:
* A bunch of Shoot cameras connected
* Video Pencil connected
* Main shot from iPhone 12 (front camera, 60fps)
* Face Follow turned on
* Wide Shot iPhone 14, (back camera 1080p)

When the slide was edited, everything started lagging terribly.

**Comment by michaelforrest** [comment]
<img width="363" alt="image" src="https://github.com/goodtohear/BeatSheetStudio/assets/9776/614ed59e-eb49-470c-8fa7-83ca7b45a0db">
Reproduced performance hit in build 27. 
Small spikes are second Shoot camera connection. Continuous pressure after I edit a bullet point.

**Comment by michaelforrest** [comment]
After changes, we don't get the sustained lag. 
<img width="633" alt="Screenshot 2023-07-21 at 12 10 45" src="https://github.com/goodtohear/BeatSheetStudio/assets/9776/684ada12-1d53-498c-afb1-421883a8fdf1">
