### ISSUE TITLE
Virtual mic issues

### ISSUE THREAD

**Issue by duhring** [goodtohear/BeatSheetStudio#54]
I am getting clean audio but so faint I had to boost +12db at three levels in LumaFusion to produce the video below. Also note severe sync issue (which disappeared after I turned off Apple voice isolation on both BSS and OBS).

https://youtu.be/rKW8I_WBLNc (recorded using Apple's voice isolation)

https://youtu.be/lYYRpAphztA (recorded without Apple's voice isolation, in plenty of room noise and no audio boosting in LumaFusion).

https://youtu.be/ShKoXYwwhYA (same raw footage but audio boosted in post)

https://youtu.be/Em2dNmiocjs (recorded using the laptop mic, Apple "Standard" mic mode... again, boosted dramatically in post).

I installed the new virtual mic and rebooted the Mac as described:
Build 31 (28 Jul 2023) 2 days ago

Major improvements to the virtual mic (install via Output menu and reboot)
Fixed issue where the mic would be opened up when editing cards or returning to the app
Starting a presentation halfway down no longer scrolls the script back to the top
Allow muting sources directly from the audio bar
Ability to sign in to Squares TV (doesn’t do anything yet!)

**Comment by michaelforrest** [comment]
Workaround for now (I think) is to go into the Audio MIDI Setup app and increase the volume of the virtual mic output.

**Comment by michaelforrest** [comment]
Closing as invalid as this is two issues requiring very different solutions.
