### ISSUE TITLE
Next Bullet icon, the >| does not show on the very right side

### ISSUE THREAD

**Issue by juergenschubert** [goodtohear/BeatSheetStudio#59]
This request is about the layout of the "Next Topic" Icon which is not at the end of the red line. Just after the last letter of the "NEXT" topic.
I would love to see the "Next Bullet: Icon >|  on the very right side of the red line like you have for the previous slide.

Go into BBS and step through the Bullets, next Bullet with the Next Bullet Icon in the red line on the right side.
![Pasted_Image_02_08_23__15_29](https://github.com/goodtohear/BeatSheetStudio/assets/17120076/516eb938-0dc6-4879-b55e-0dd9acbcc745)

**Comment by michaelforrest** [comment]
I don't understand this request - is this about the layout /position of the icon? When you say "the red line" do you mean the big "Next" button in the main window / HUD? 
<img width="1012" alt="Screenshot 2023-08-02 at 10 25 14" src="https://github.com/goodtohear/BeatSheetStudio/assets/9776/ea5a71b2-500f-48c9-98ed-02e316b2a160">

**Comment by michaelforrest** [comment]
The big pink bar *is* the `>| ` button so there doesn't need to be another one mirroring the one on the left, if that's what you mean?

**Comment by juergenschubert** [comment]
![Pasted_Image_02_08_23__15_29](https://github.com/goodtohear/BeatSheetStudio/assets/17120076/e5d222cf-0574-46eb-97a7-f156cceee427)

**Comment by michaelforrest** [comment]
The actions are not asymmetrical, hence the layout is not asymmetrical (going back is a much less common interaction than going forwards)

**Comment by michaelforrest** [comment]
Oh I think I understand now. This is ultimately a matter of opinion though! I think it's easier to see where it is, even if it moves about depending on the text in the button.
