### ISSUE TITLE
Video Pencil triggered by "Video Pencil Camera" shows the HUD on the iPAD

### ISSUE THREAD

**Issue by juergenschubert** [goodtohear/BeatSheetStudio#60]
and I have to click the X on every card. This will make it very hard to draw.
A "default hide HUD" on the iPad or BSS for the iPad HUD would help

Reproduce the issue
Start BBS
start a camera
Start BSS with a card containing text

switch to Video Pencil on iPad
Choose the Video Pencil camera

the text of the card will show on the very lower bottom on the video pencil in a black box with all the text

**Comment by michaelforrest** [comment]
There is a menu option to turn this off now.
