### ISSUE TITLE
MIssing "save as" menu option

### ISSUE THREAD

**Issue by juergenschubert** [goodtohear/BeatSheetStudio#62]
**Describe the bug**
opening a Beat Sheet document with BSS by right clicking on the file and choose BSS instead of beatsheet will open the document but I do miss the option to save it in the BSS format. Would be great to have a save as where you can choose, text, BeatSheet or BSS format you wanna write the file as.

**Comment by michaelforrest** [comment]
`.bss` files are not backwards compatible with `.beatsheet` documents. You can use the "Copy all" menu item to get the entire document as plain text.

What is the reason you want to go back to a `.beatsheet` file?
