### ISSUE TITLE
Weird timing on Video Pencil Camera preview (but smooth on iPad)

### ISSUE THREAD

**Issue by michaelforrest** [goodtohear/BeatSheetStudio#78]
*VIDEO PENCIL CAMERA*

> I'm having issues with video pencil camera on my mac. I've got latest versions of apps on ipad & mac. When I choose the facetime camera on my imac it shows up as a smooth feed on the ipad. But in the preview window on my imac I look like Maxheadroom. The video is stuttering. Any ideas?

I think this is due to different timing coming from the Elgato which then gets combined with VPC's timing - this could result in weirdness.

**Comment by Info3SR** [comment]
I have an issue with video pencil camera. The video feed is stuttering when I use the imac's built in Facetime camera.
I'm on a 2020 27" 5k imac with a 10-core intel i9.

I've included a screencast of what's happening.

https://github.com/goodtohear/BeatSheetStudio/assets/14974795/d8c61296-1a84-4e15-84e1-b9746ef35ac3

**Comment by michaelforrest** [comment]
Ok I know what this was. New beta build incoming...

**Comment by Info3SR** [comment]
I downloaded and tried version 1.3.6 to fix the 'Max Headroom Glitch' 😂
Unfortunately it hasn't fully fixed the problem.

I uninstalled the virtual camera extension and then the app. I downloaded a clean version from the app store.
Now there is a stuttering blinkingrefresh of the entire screen.

**Comment by michaelforrest** [comment]
> I downloaded and tried version 1.3.6 to fix the 'Max Headroom Glitch' 😂 Unfortunately it hasn't fully fixed the problem.
> 
> I uninstalled the virtual camera extension and then the app. I downloaded a clean version from the app store. Now there is a stuttering blinkingrefresh of the entire screen.

Honestly this is starting to feel like a hardware issue on your end :-(

But if you can share another video showing what's happening, I might be able to determine the cause. If you can include the debugging view with your capture that would be helpful.
