### ISSUE TITLE
Plugging in headphones can cause a crash

### ISSUE THREAD

**Issue by duhring** [goodtohear/BeatSheetStudio#79]
I set up the virtual mic as input to Zoom. After a restart, it was working before BSS crashed.

**To Reproduce**
1. Start a zoom meeting
2. Set up BSS as the camera and the virtual mic for audio
3. Test sound from both the microphone in BSS and audio from a video on a card
4. Monitor audio with earphones
5. Note audio levels in zoom
6. Does it crash?

Full crash report sent via email:

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Beat Sheet Studio [14033]
Path:                  /Applications/Beat Sheet Studio.app/Contents/MacOS/Beat Sheet Studio
Identifier:            tv.squares.BeatSheetStudio
Version:               0.9.8 (33)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-08-14 16:02:41.0570 -0700
OS Version:            macOS 13.4.1 (22F770820d)
Report Version:        12
Anonymous UUID:        5FD35A38-960D-D195-6745-43AED17D4705

Time Awake Since Boot: 70000 seconds

System Integrity Protection: enabled

Crashed Thread:        9  com.apple.audio.IOThread.client

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000008
Exception Codes:       0x0000000000000001, 0x0000000000000008

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [14033]

VM Region Info: 0x8 is not in any region.  Bytes before following region: 105553518919672
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      MALLOC_NANO (reserved)   600018000000-600020000000 [128.0M] rw-/rwx SM=NUL  ...(unallocated)

**Comment by michaelforrest** [comment]
@duhring please try to make your issue titles descriptive! 

I renamed this from "BSS Crash - v 0.9.8 (33)" to "Plugging in headphones can cause a crash"

Otherwise how do I know what I'm looking at from the list view?

![image](https://github.com/goodtohear/BeatSheetStudio/assets/9776/319c7296-6c3b-4754-ab3d-ebc95fae31fe)
