### ISSUE TITLE
New apps or windows not showing without restarting BSS

### ISSUE THREAD

**Issue by duhring** [goodtohear/BeatSheetStudio#8]
I wanted to fire up an app and share it, but BSS didn't show the window in the drop down list.

**Comment by michaelforrest** [comment]
@samilao101 it would be good to find a consistent SwiftUI lifecycle way to ensure pickers and menus cause their related state objects to refresh when used. I have been resorting to onHover but this feels sketchy!

**Comment by michaelforrest** [comment]
OR we find a ScreenCaptureKit way to update state as available windows change, which would be a more "correct" way to do this.

**Comment by michaelforrest** [comment]
See beatsheet/BeatSheet/Features/WindowCapture/ScreenCaptureState.swift

**Comment by samilao101** [comment]
**So Apple's sample app [CaptureSample](https://developer.apple.com/documentation/screencapturekit/capturing_screen_content_in_macos) uses:**
![Screenshot 2023-07-15 at 9 11 04 AM](https://github.com/goodtohear/BeatSheetStudio/assets/21692781/a6c1dc4a-257c-4a7d-86ae-45e59e82f221)

which just fires:
![Screenshot 2023-07-15 at 10 14 27 AM](https://github.com/goodtohear/BeatSheetStudio/assets/21692781/faae655c-a861-4cf2-8715-aad7516f8677)



Which is not very inspiring, so I wanted to check with you before implementing.  I went through their sessions and tried reading the documentation, and google and could not find anything like a protocol-delegate. The SCContentSharingPicker might be something to consider in the future (beta).

**Comment by michaelforrest** [comment]
I don't love the idea of polling but if that's how Apple does it... 
One problem I would anticipate is that a lot of view hierarchy could get repeatedly rebuilt unnecessarily so I would check whether anything has changed before assigning to any @Published variables.

**Comment by samilao101** [comment]
That's true, I will try implementing with that check.
