### ISSUE TITLE
Second camera not showing on cards

### ISSUE THREAD

**Issue by duhring** [goodtohear/BeatSheetStudio#80]
When I choose to present a second camera on a card, it is not presented.

1. Go to a new BSS document
2. Click on the card
3. Select the "Camera" tab in the pop-up window
4. Choose a second camera
5. Choose "picture in picture"
6. Start the presentation
7. See error (only the Main Camera remains on screen).

I expect the second camera source to fill the canvas, with the Main Camera appearing as PiP only (if selected). Earlier builds were working fine. I am on build (34).

I want to test switching between two "second cameras" with Main Camera as PiP or brought up with the "Aside" gesture.

**Comment by michaelforrest** [comment]
I discovered this yesterday too. I'll pop out a fix asap!
