### ISSUE TITLE
CPU load with new demo mode

### ISSUE THREAD

**Issue by duhring** [goodtohear/BeatSheetStudio#87]
My Mac fan kicked in while testing Version 0.9.8 (38). I was using Demo mode, displaying the Mac app and the iPad.

<img width="910" alt="Screenshot 2023-09-07 at 10 49 13 AM" src="https://github.com/goodtohear/BeatSheetStudio/assets/2724263/1c8d6af7-d4f9-47d1-a0d0-02aa9bc20616">
<img width="1033" alt="Screenshot 2023-09-07 at 10 48 53 AM" src="https://github.com/goodtohear/BeatSheetStudio/assets/2724263/d78baa39-bf16-4918-8655-2dee7f7fb202">
<img width="1033" alt="Screenshot 2023-09-07 at 10 49 00 AM" src="https://github.com/goodtohear/BeatSheetStudio/assets/2724263/24cd446d-14b4-423b-9282-b33d7e45f0a9">

**Comment by michaelforrest** [comment]
A lot has changed since this bug report so I probably need a new one with any new issues.
