### ISSUE TITLE
Video Pencil Overlay Not Active / Working in Ecamm Live Once Beat Sheet Studio Is Open

### ISSUE THREAD

**Issue by NeilJFarrimond** [goodtohear/BeatSheetStudio#88]
Launching Beat Sheet Studio when Video Pencil is running removes the ability to use Video Pencil within Ecamm Live. Video explainer here.  https://drive.google.com/file/d/1Fr3-gtPfNX6IMRxVhkwqDohDYiS2N5Ul/view?usp=sharing

**Comment by michaelforrest** [comment]
Workaround would be to not connect over USB, which will result in a confirmation prompt next time you connect.

**Comment by michaelforrest** [comment]
Behaviour will be different depending on whether you use NDI or not. You might just need to re-enable the NDI feed from within Video Pencil (and reselect Ecamm as the camera source).

**Comment by NeilJFarrimond** [comment]
NDI Fixed the issue thanks.
