### ISSUE TITLE
Unable to Install Camera extension 

### ISSUE THREAD

**Issue by duhring** [goodtohear/BeatSheetStudio#90]
Version 0.9.10 (43) installation process stalled after installing the camera extension and giving permission. The condition evaporated after a long restart. After completely uninstalling and starting again, I found I had to work diligently to completely uninstall the camera extension, then to completely authorize the installation of the new extension. Sometimes the Systems Settings showed the extension was enabled, when the app didn't. In the end, I used the 'Output>Camera Extension' method to uninstall the old extension and verified this after a computer reboot before attempting to install the extension.

1. Download CueCam Presenter
2. Click on 'Camera'
3. See 'Camera Extension required.'
4. Click on "Settings"
5. In System Settings, go to 'Privacy & Security'
6. Scroll to the Camera, enable CueCam Presenter
7. Restart computer
8. Launch CueCam Presenter
9. Click on 'Camera'
10. Note extension not installed

<img width="903" alt="Screenshot 2023-09-14 at 12 25 20 PM" src="https://github.com/goodtohear/BeatSheetStudio/assets/2724263/fd3b74d4-ee98-498f-bc16-dd0f8bd6370a">

**Comment by michaelforrest** [comment]
First, thank you for an excellent bug report!

I'll start by clearing up what permission is what. The permission you're looking at is whether or not CueCam can access your camera(s), so it has on effect on the camera extension.

What you're looking for is the "Allow" button that appears if you go to the Settings app (linked via the button on this screen).

In the case of this problem, try using the blue link "click here to try reinstalling".

If that doesn't work, try using the Output menu item Virtual Camera -> Uninstall Camera Extension and then try the blue link again. 

If that still doesn't work, I might need you to send a video showing how each step behaves...

**Comment by michaelforrest** [comment]
I think I missed that you figured out the uninstall thing.
This is (I hope) just a side effect of the renaming of the app so I don't think it will affect new users.
If it does, we can reopen this issue.
