### ISSUE TITLE
No way to remove Second Camera from a card

### ISSUE THREAD

**Issue by duhring** [goodtohear/BeatSheetStudio#98]
When a Second Camera is added to a card, it cannot be removed without deleting the entire card.

1. Create a presentation
2. Add a Second Camera to a card
3. Try to remove the second camera

I want to back out of a choice, like I can with Slide, Video, Screen, Music and Triggers options.
![Screenshot 2023-10-16 at 6 29 11 PM](https://github.com/goodtohear/BeatSheetStudio/assets/2724263/a2cac670-88b7-4ec8-9e19-1299484ecfd1)

**Comment by michaelforrest** [comment]
There is no "remove" button but you can select the blank first row in the Second Camera dropdown.

**Comment by duhring** [comment]
Ha! I never… there it is!Cheers,JohnSent from my iPhoneOn Oct 16, 2023, at 11:10 PM, Michael Forrest ***@***.***> wrote:﻿
Closed #98 as completed.
