### ISSUE TITLE
Version 0.9.12 (45) virtual mic install failed 

### ISSUE THREAD

**Issue by duhring** [goodtohear/BeatSheetStudio#99]
I uninstalled the virtual mic (CueCam was crashing upon launch). After installing the virtual mic from this build, everything is more stable but the virtual mic output is not functioning.

1. Uninstall the virtual mic
2. Restart the computer
3. Launch CueCam
4. Install the Virtual Mic
5. Note audio levels

See:

[https://youtu.be/NM5vaIT1Pd4?si=O5hurLGNPFlzACYm](https://youtu.be/NM5vaIT1Pd4?si=LN1so1H0gInWS2sd)

**Comment by michaelforrest** [comment]
If you quit CueCam and QuickTime and anything else using the virtual mic, before relaunching CueCam, does it start working again?

**Comment by duhring** [comment]
No. Even after full computer reboots. Sent from my iPhoneOn Oct 18, 2023, at 12:19 AM, Michael Forrest ***@***.***> wrote:﻿
If you quit CueCam and QuickTime and anything else using the virtual mic, before relaunching CueCam, does it start working again?

**Comment by michaelforrest** [comment]
I'm guessing this is resolved now?

**Comment by duhring** [comment]
👍Sent from my iPhoneOn Oct 23, 2023, at 2:59 AM, Michael Forrest ***@***.***> wrote:﻿
I'm guessing this is resolved now?
